accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"   


urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name= "logout"),
    path("admin-dashboard", views.admin_dashboard, name="admin-dashboard"),
    path("admin/view_iso/<int:pk>", views.admin_view_iso, name="admin_view_iso"),
]

greenmark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('dev_admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('iso/', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"   


urlpatterns = [
    # path("iso_start", views.iso_start, name="iso_start"),
    # path("iso_step_one", views.iso_step_one, name="iso_one"),
    path("iso_buss_info", views.iso_buss_info, name="iso_buss_info"),
    path("iso_step_two", views.iso_step_two, name="iso_step_two"),
    path("iso_step_three", views.iso_step_three, name="iso_step_three"),
    path("iso_step_four", views.iso_step_four, name="iso_step_four"),
    path("print_doc", views.print_doc, name="print_doc"),
    path("view_plan", views.view_plan, name="view_plan"),
    path("view_do", views.view_do, name="view_do"),
    path("view_check", views.view_check, name="view_check"),
    path("view_act", views.view_act, name="view_act"),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

accounts/views.py
from django.shortcuts import  render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import Group


from main.models import *
from main.forms import *
from .forms import NewUserForm

def homepage(request):
    return render(request, "accounts/home.html")

def is_admin(user):
    return user.groups.filter(name='ADMIN').exists()

@login_required
def dashboard(request):
	modelA = BussInfo.objects.filter(user=request.user)
	modelB = EnvThreats.objects.filter(user=request.user)
	modelC = AuditReview.objects.filter(user=request.user)
	context = {
        'modelA': modelA,
        'modelB': modelB,
		'modelC': modelC,
    }
	return render(request, "accounts/dashboard.html", context)

@login_required
@user_passes_test(is_admin)
def admin_dashboard(request):
	users = User.objects.all().order_by("-id")
	modelA = BussInfo.objects.all().order_by("-id")
	modelC = AuditReview.objects.all().order_by("-id")
	context = {
		'users': users,
		'modelA': modelA,
		'modelC': modelC,
	}
	return render(request, "accounts/admin_dashboard.html", context)


@login_required
@user_passes_test(is_admin)
def admin_view_iso(request, pk):
	user = User.objects.get(id=pk)
	modelA = BussInfo.objects.filter(id=pk)
	modelB = EnvCompOblig.objects.filter(id=pk)
	modelC = AspImpact.objects.filter(id=pk)
	modelD = EnvThreats.objects.filter(id=pk)
	modelE = Objectives.objects.filter(id=pk)
	modelF = CompanyPolicy.objects.filter(id=pk)
	modelG = EmergencyResponse.objects.filter(id=pk)
	modelH = Communications.objects.filter(id=pk)
	modelI = Documentation.objects.filter(id=pk)
	modelJ = AuditReview.objects.filter(id=pk)
	modelK = Location.objects.filter(id=pk)
	context = {
		'user': user,
        'modelA': modelA,
        'modelB': modelB,
        'modelC': modelC,
        'modelD': modelD,
        'modelE': modelE,
        'modelF': modelF,
        'modelG': modelG,
        'modelH': modelH,
        'modelI': modelI,
        'modelJ': modelJ,
        'modelK': modelK,
    }
	return render(request, 'accounts/admin_view_iso.html', context)



def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("accounts:dashboard")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="accounts/register.html", context={"register_form":form})

# my_admin_group = Group.objects.get_or_create(name='ADMIN')



def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				if is_admin(request.user):
					return redirect("accounts:admin-dashboard")
				else:
					return redirect("accounts:dashboard")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="accounts/login.html", context={"login_form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("accounts:homepage")

accounts/templates/accounts/admin_dashboard.html
{% extends 'accounts/base.html' %}

{% block css %}

{% endblock css %}
{% block title %} Admin Dashboard {% endblock title %}

{% block content %}

<!--Dashboard--> 

  <div class="nav-area">
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Greenmark Online</a>
      <span class="left-float"><a href="{% url 'accounts:logout' %}">Logout</a></spa>
    </nav>
  </div>
  
  <br> 
  
  <div class="container">
    <div class="jumbotron">
        <h2>Admin Dashboard</h2>
        <hr>
        
        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">User</th>
                <th scope="col">Business Name</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
            {% for a in modelA %}
              <tr>
                <td>{{ a.user }}</td>
                <td>{{ a.buss_name }}</td>
                <td><a href="{% url 'accounts:admin_view_iso' a.id %}" class="btn btn-success">Success</a> </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>

          
        
        
    </div>
  </div>



<br>

{% endblock content %}

accounts/templates/accounts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block css %}{% endblock css %}

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
   {% block content %}{% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

accounts/templates/accounts/dashboard.html
{% extends 'accounts/base.html' %}

{% block css %}

{% endblock css %}
{% block title %} Dashboard {% endblock title %}

{% block content %}

<!--Dashboard--> 

  <div class="nav-area">
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Greenmark Online</a>
      <span class="left-float"><a href="{% url 'accounts:logout' %}">Logout</a></spa>
    </nav>
  </div>
  
  <br> 
  
  <div class="container">
    <div class="jumbotron">
        <h2>Dashboard - Welcome {{ user.username.title }} </h2>
        <hr>

        <h1>ISO 2015: ENVIRONMENTAL MANAGEMENT FORM</h1>
        
        {% if modelA and not modelB and not modelC %}
        <div class="alert alert-success" role="alert">
            You have an ongoing session <a href="{% url 'main:iso_step_two' %}" class="btn btn-success"> <hr> Step 1 Completed 
            <a href="{% url 'main:iso_step_two' %}" class="btn btn-success"> Continue to Step 2 </a>
        </div>
        {% elif modelA and modelB and not modelC %}
        <div class="alert alert-success" role="alert">
            You have an ongoing session <a href="{% url 'main:iso_step_two' %}" class="btn btn-success"> <hr> Step 2 Completed 
            <a href="{% url 'main:iso_step_three' %}" class="btn btn-success"> Continue to Step 3 </a>
        </div>
        {% elif modelA and modelB and modelC %}
        <div class="alert alert-success" role="alert">
            You have successfully completed the ISO form <hr>
            <a href="{% url 'main:print_doc' %}" class="btn btn-success"> Print ISO Document </a>
        </div>
        {% elif not modelA and not modelB and not modelC %}
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal">
            Fill ISO form
        </button>
        {% endif %}
        
        
  
        <!-- Modal -->

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">ISO 14001: Environmental Management Form</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    <h2>Getting Started</h2>
                    <p><strong><em>Plan - Do - Check - Act</em></strong></p>
                    <hr>
                    <p><strong>STEP 1 - Plan</strong></p>
                    <p>Business Information, Scope and Commitment</p>
                    <p>Compliance Obligations, Activities, Aspects and Impacts</p>
        
                    <p><strong>STEP 2 - Do</strong></p>
                    <p>Risk Assessment, Objective and Policy,</p>
                    <p>Emergency Response, Nonconformities,</p>
                    <p>Communication, Documnentation</p>
        
                    <p><strong>STEP 3 - Check</strong></p>
                    <p>Audits and Annual Review</p>
                    <p>greenmark registry commitment</p>
        
                    <p><strong>STEP 4 - ACT</strong></p>
                    <p>Continual improvement</p>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a href="{% url 'main:iso_buss_info' %}" type="button" class="btn btn-success">Get Started</a>
                </div>
            </div>
            </div>
        </div>
        
    </div>
  </div>



{% if modelA and not modelB and not modelC %}
<div class="container">
    <div class="row">
        <div class="col-sm-3">
        <div class="card">
            <div class="card-body">
            <h5 class="card-title">Plan</h5>
            <p class="card-text">Business Information, Scope and Commitment,
            Compliance Obligations, Activities, Aspects and Impacts</p>
            <a href="{% url 'main:view_plan' %}" class="btn btn-success">View</a>
            </div>
        </div>
        </div>
    </div>
</div>
{% elif modelA and modelB and not modelC %}
<div class="container">
    <div class="row">
        <div class="col-sm-3">
        <div class="card">
            <div class="card-body">
            <h5 class="card-title">Plan</h5>
            <p class="card-text">Business Information, Scope and Commitment,
            Compliance Obligations, Activities, Aspects and Impacts</p>
            <a href="{% url 'main:view_plan' %}" class="btn btn-success">View</a>
            </div>
        </div>
        </div>
        <div class="col-sm-3">
        <div class="card">
            <div class="card-body">
            <h5 class="card-title">Do</h5>
            <p class="card-text">Risk Assessment, Objective and Policy,
            Emergency Response, Nonconformities, Communication, Documnentation</p>
            <a href="{% url 'main:view_do' %}" class="btn btn-success">View</a>
            </div>
        </div>
        </div>
    </div>
</div>
{% elif modelA and modelB and modelC %}
<div class="container">
    <div class="row">
        <div class="col-sm-3">
        <div class="card">
            <div class="card-body">
            <h5 class="card-title">Plan</h5>
            <p class="card-text">Business Information, Scope and Commitment,
            Compliance Obligations, Activities, Aspects and Impacts</p>
            <a href="{% url 'main:view_plan' %}" class="btn btn-success">View</a>
            </div>
        </div>
        </div>
        <div class="col-sm-3">
        <div class="card">
            <div class="card-body">
            <h5 class="card-title">Do</h5>
            <p class="card-text">Risk Assessment, Objective and Policy,
            Emergency Response, Nonconformities, Communication, Documnentation</p>
            <a href="{% url 'main:view_do' %}" class="btn btn-success">View</a>
            </div>
        </div>
        </div>
        <div class="col-sm-3">
            <div class="card">
                <div class="card-body">
                <h5 class="card-title">Check</h5>
                <p class="card-text">Audits and Annual Review, 
                    <br>greenmark registry commitment</p>
                <a href="{% url 'main:view_check' %}" class="btn btn-success">View</a>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="card">
                <div class="card-body">
                <h5 class="card-title">Act</h5>
                <p class="card-text">Continual improvement</p>
                <a href="{% url 'main:view_act' %}" class="btn btn-success">View</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% elif not modelA and not modelB and not modelC %}
<div class="container">
    <div class="alert alert-success" role="alert">
        You do not have any saved records
    </div>
</div>


{% endif %}


<br>
<br>

{% endblock content %}

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}

{% block css %}

{% endblock css %}
{% block title %} Homepage {% endblock title %}

{% block content %}

<!--Dashboard--> 

  <div class="nav-area">
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Greenmark Online</a>
    </nav>
  </div>

  <br>
  
    <div class="container jumbotron">
      <h1 class="display-4">Hello, world!</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <p class="lead">

        {% if user.is_authenticated %}
        <a class="btn btn-success" href="{% url 'accounts:dashboard' %}">Go to Dashboard</a>
        <a class="btn btn-outline-success" href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
        <a class="btn btn-success" href="{% url 'accounts:register' %}">Register</a>
        <a class="btn btn-outline-success" href="{% url 'accounts:login' %}">Login</a>
        {% endif %}
      </p>
    </div>


{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}      

{% block title %} Login {% endblock title %}

{% block content %}

<!--Login--> 
<div class="container py-5">
    <h1>Login</h1>
    <form method="POST">
      {% csrf_token %}
      {{ login_form|crispy }}
      <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>

{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}      

{% block title %} Register {% endblock title %}

{% block content %}

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock content %}