accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"   


urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name= "logout"),
    path("admin-dashboard", views.admin_dashboard, name="admin-dashboard"),
    path("admin/view_iso/<int:pk>", views.admin_view_iso, name="admin_view_iso"),
]

greenmark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('dev_admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('iso/', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"   


urlpatterns = [
    # path("iso_start", views.iso_start, name="iso_start"),
    # path("iso_step_one", views.iso_step_one, name="iso_one"),
    path("iso_buss_info", views.iso_buss_info, name="iso_buss_info"),
    path("iso_step_two", views.iso_step_two, name="iso_step_two"),
    path("iso_step_three", views.iso_step_three, name="iso_step_three"),
    path("iso_step_four", views.iso_step_four, name="iso_step_four"),
    path("print_doc", views.print_doc, name="print_doc"),
    path("view_plan", views.view_plan, name="view_plan"),
    path("view_do", views.view_do, name="view_do"),
    path("view_check", views.view_check, name="view_check"),
    path("view_act", views.view_act, name="view_act"),
]

main/forms.py
from dataclasses import field
from pyexpat import model
from django.forms import ModelForm
from django import forms

from .models import *

class BussInfoForm(ModelForm):
    class Meta:
        model = BussInfo
        exclude = ['user']
class EnvCompObligForm(ModelForm):
    # person_rep = forms.ChoiceField(widget=forms.RadioSelect(choices=PERSON_RESP_FOR_ENV_COMP))
    class Meta:
        model = EnvCompOblig
        exclude = ['user']

class AspImpactForm(ModelForm):
    class Meta:
        model = AspImpact
        exclude = ['user']

class EnvThreatsForm(ModelForm):
    class Meta:
        model = EnvThreats
        exclude = ['user']

class TrainersForm(ModelForm):
    class Meta:
        model = AspImpact
        exclude = ['user']

class ObjectivesForm(ModelForm):
    class Meta:
        model = Objectives
        exclude = ['user']

class CompanyPolicyForm(ModelForm):
    class Meta:
        model = CompanyPolicy
        exclude = ['user']

class EmergencyResponseForm(ModelForm):
    class Meta:
        model = EmergencyResponse
        exclude = ['user']

class CommunicationsForm(ModelForm):
    class Meta:
        model = Communications
        exclude = ['user']

class DocumentationForm(ModelForm):
    class Meta:
        model = Documentation
        exclude = ['user']

class AuditReviewForm(ModelForm):
    class Meta:
        model = AuditReview
        exclude = ['user']

class LocationForm(ModelForm):
    class Meta:
        model = Location
        exclude = ['user']

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.template.loader import get_template
from django.http import HttpResponse
from django.contrib.auth.models import User

from .models import *
from .forms import *

@login_required
def iso_start(request):
    return render(request, 'main/iso_plan.html')

@login_required
def iso_buss_info(request):
    user = request.user
    formA = BussInfoForm
    formB = EnvCompObligForm
    formC = AspImpactForm
    formD = LocationForm
    if request.method == "POST":
        formA = BussInfoForm(request.POST)
        formB = EnvCompObligForm(request.POST)
        formC = AspImpactForm(request.POST)
        formD = LocationForm(request.POST)
        if formA.is_valid() and formB.is_valid() and formC.is_valid() and formD.is_valid():
            a = formA.save(commit=False)
            a.user = user
            b = formB.save(commit=False)
            b.user = user
            c = formC.save(commit=False)
            c.user = user
            d = formD.save(commit=False)
            d.user = user
            a.save()
            b.save()
            c.save()
            d.save()
            return redirect("main:iso_step_two")
    context = {
        'user': user,
        'formA': formA,
        'formB': formB,
        'formC': formC,
        'formD': formD,  
    }
    return render(request, 'main/iso_buss_info.html', context)

@login_required
def iso_step_two(request):
    user = request.user
    buss_info = BussInfo.objects.filter(user=request.user)
    asp_imp = AspImpact.objects.filter(user=request.user)
    formA = EnvThreatsForm
    formB = ObjectivesForm
    formC = CompanyPolicyForm
    formD = EmergencyResponseForm
    formE = CommunicationsForm
    formF = DocumentationForm
    if request.method == "POST":
        formA = EnvThreatsForm(request.POST)
        formB = ObjectivesForm(request.POST)
        formC = CompanyPolicyForm(request.POST)
        formD = EmergencyResponseForm(request.POST)
        formE = CommunicationsForm(request.POST)
        formF = DocumentationForm(request.POST)
        a_valid = formA.is_valid()
        b_valid = formB.is_valid()
        c_valid = formC.is_valid()
        d_valid = formD.is_valid()
        e_valid = formE.is_valid()
        f_valid = formF.is_valid()
        if a_valid and b_valid and c_valid and d_valid and e_valid and f_valid:
            a = formA.save(commit=False)
            a.user = user
            b = formB.save(commit=False)
            b.user = user
            c = formC.save(commit=False)
            c.user = user
            d = formD.save(commit=False)
            d.user = user
            e = formE.save(commit=False)
            e.user = user
            f = formF.save(commit=False)
            f.user = user
            a.save()
            b.save()
            c.save()
            d.save()
            e.save()
            f.save()
            return redirect("main:iso_step_three")
    context = {
        'user': user,
        'buss_info': buss_info,
        'formA': formA,
        'formB': formB,
        'formC': formC,
        'formD': formD,
        'formE': formE,
        'formF': formF,
        'asp_imp': asp_imp,       
    }
    return render(request, 'main/iso_do.html', context)


@login_required
def iso_step_three(request):
    user = request.user
    formA = AuditReviewForm
    if request.method == "POST":
        formA = AuditReviewForm(request.POST)
        if formA.is_valid():
            a = formA.save(commit=False)
            a.user = user
            a.save()
            return redirect("main:iso_step_four")
    context = {
        'user': user,
        'formA': formA,       
    }
    return render(request, 'main/iso_check.html', context)


@login_required
def iso_step_four(request):
    user = request.user
    modelA = BussInfo.objects.filter(user=request.user)
    context = {
        'user': user,
        'modelA': modelA,
    }
    return render(request, 'main/iso_act.html', context)



# @login_required
# def iso_step_one(request):
#     user = request.user
#     formA = BussInfoForm
#     formB = AspImpactForm
#     if request.method == "POST":
#         formA = BussInfoForm(request.POST)
#         formB = AspImpactForm(request.POST)
#         if formA.is_valid() and formB.is_valid():
#             a = formA.save(commit=False)
#             a.user = user
#             b = formB.save(commit=False)
#             b.user = user
#             a.save()
#             b.save()
#             return redirect("main:print_doc")
#     context = {
#         'user': user,
#         'formA': formA,
#         'formB': formB        
#     }
#     return render(request, 'main/iso_form.html', context)

@login_required
def print_doc(request):
    user = request.user
    modelA = BussInfo.objects.filter(user=request.user)
    modelB = EnvCompOblig.objects.filter(user=request.user)
    modelC = AspImpact.objects.filter(user=request.user)
    modelD = EnvThreats.objects.filter(user=request.user)
    modelE = Objectives.objects.filter(user=request.user)
    modelF = CompanyPolicy.objects.filter(user=request.user)
    modelG = EmergencyResponse.objects.filter(user=request.user)
    modelH = Communications.objects.filter(user=request.user)
    modelI = Documentation.objects.filter(user=request.user)
    modelJ = AuditReview.objects.filter(user=request.user)
    modelK = Location.objects.filter(user=request.user)
    context = {
        'user': user,
        'modelA': modelA,
        'modelB': modelB,
        'modelC': modelC,
        'modelD': modelD,
        'modelE': modelE,
        'modelF': modelF,
        'modelG': modelG,
        'modelH': modelH,
        'modelI': modelI,
        'modelJ': modelJ,
        'modelK': modelK,
    }
    return render(request, 'main/print_doc.html', context)

@login_required
def view_plan(request):
    user = request.user
    modelA = BussInfo.objects.filter(user=request.user)
    modelB = EnvCompOblig.objects.filter(user=request.user)
    modelC = AspImpact.objects.filter(user=request.user)
    modelD = Location.objects.filter(user=request.user)
    context = {
        'user': user,
        'modelA': modelA,
        'modelB': modelB,
        'modelC': modelC,
        'modelD': modelD,
    }
    return render(request, 'main/view_plan.html', context)


@login_required
def view_do(request):
    user = request.user
    modelA = EnvThreats.objects.filter(user=request.user)
    modelB = Objectives.objects.filter(user=request.user)
    modelC = CompanyPolicy.objects.filter(user=request.user)
    modelD = EmergencyResponse.objects.filter(user=request.user)
    modelE = Communications.objects.filter(user=request.user)
    modelF = Documentation.objects.filter(user=request.user)
    asp_imp = AspImpact.objects.filter(user=request.user)
    buss_info = BussInfo.objects.filter(user=request.user)
    context = {
        'user': user,
        'modelA': modelA,
        'modelB': modelB,
        'modelC': modelC,
        'modelD': modelD,
        'modelE': modelE,
        'modelF': modelF,
        'asp_imp': asp_imp,
        'buss_info': buss_info,
    }
    return render(request, 'main/view_do.html', context)

@login_required
def view_check(request):
    user = request.user
    modelA = AuditReview.objects.filter(user=request.user)
    context = {
        'user': user,
        'modelA': modelA,
    }
    return render(request, 'main/view_check.html', context)


@login_required
def view_act(request):
    user = request.user
    modelA = BussInfo.objects.filter(user=request.user)
    context = {
        'user': user,
        'modelA': modelA,
    }
    return render(request, 'main/view_act.html', context)

main/templates/main/iso_act.html
{% extends 'main/iso_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Do{% endblock title %}

{% block content %}
<br> 
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">STEP 2 - Do</a></li>
        <li class="breadcrumb-item"><a href="{% url 'accounts:dashboard' %}">Back to dashboard</a></li>
        </ol>
    </nav>
</div>


<form class="form">

    <h2>STEP 3 - Check</h2>

    <br>

    <!-- Sectoin for ACT -->
    <div>
        <h3>ANNUAL MANAGEMENT REVIEW</h3>
        <p><strong>This review should be completed at the end of the year:</strong> it can be done during or right after the fourth Quarter Audit or soon after. The Key Decision Maker/s and the Environment Manager do the following:
        <ol>
            <li>Evaluate the overall environmental performance in light of the policy and commitment to objectives</li>

            <li>Identify and commit to new objectives taking into account changes in the business during the last year</li>

            <li>Sign off on starting a new ISO 14001:2015 cycle and celebrate success</li>
        </ol>
        </p>
        {% for bus_info in modelA  %}

        <h3>CONTINUAL IMPROVEMENT</h3>
        <p> <strong> {{ bus_info.buss_name }} </strong> commits to having quarterly and annual reviews, audited by greenmark. </p>

        <p> <strong> {{ bus_info.buss_name }} </strong>   commits to continually improve its environmental management system, evidenced by the greenmark online registry.</p>

        {% endfor %}
        <br><br>
        <div class="btns-group">
            <a href="{% url 'main:print_doc' %}" type="submit" class="btn">Launch your ISO 14001:2015 EMS</a>
        </div>
    </div>

</form>

{% endblock content %}

main/templates/main/iso_base.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'styling.css' %}" />
    <script src="{% static 'script.js' %}" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'html2pdf.bundle.min.js' %}"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %}</title>

</head>

<body id="fileToBeDowloaded">

    {% block content %}{% endblock content %}

    <script>
        const btn = document.getElementById("pdfbutton");
        
        btn.addEventListener("click", function(){
        var element = document.getElementById('body');
        html2pdf().from(element).save('iso_document.pdf');
        });
    </script>
    
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

main/templates/main/iso_check.html
{% extends 'main/iso_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Check{% endblock title %}

{% block content %}
<br> 
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">STEP 3 - Check</a></li>
        <li class="breadcrumb-item"><a href="{% url 'accounts:dashboard' %}">Back to dashboard</a></li>
        </ol>
    </nav>
</div>


<form class="form" method="post">
    {% csrf_token %}
    <h2>STEP 3 - Check</h2>

    <br>

    <!-- Section for CHECK -->
    <h2>AUDITS AND ANNUAL MANAGEMENT REVIEW</h2>
            <p>Auditing is a key part of the ISO 14001:2015 System. Its function is to evaluate performance against the objectives that were chosen at the beginning of your annual cycle and conformance with compliance obligations.  The major audit is at the end of the year when all objectives are to be fully completed. To ensure compliance, periodic audits - at the end of every quarter - are undertaken during the year, to look at progress in achieving objectives.  The auditors are people working in the business, and no special auditing qualifications are necessary. Ideally another person than the one responsible for the objective should do the audit for the objective being evaluated. Auditors can be different people at different checkpoints.  As part of your annual subscription, greenmark will review your audit results.</p>

            <p><strong>Note:</strong> the <strong>ISO 14001:2015</strong>  Standard does not require, nor does it favour the option of using official registrars over the options of self-declaration or other third party.  Below please find an example of periodic audits followed by blanks to be filled out at the end of each period and at the end of the year. <br>
            <strong>In this example</strong> the company started its ISO 14001:2015 Environmental Management on September 1st. <strong> (Note that the start can be at any time during the year).</strong></p>

            <p><strong>Checkpoint 1 Example:</strong>for a company starting its EMS (Environmental Management System) on September 1, 2022: <br>
            First Quarter Audit for the period September 1 – November 30,2022, <br>
            <strong> Annual cycle:</strong> September 1 2022 – August 31 2023 <br>
            <strong> Auditor:</strong> Mercedez Garcia <br>
                
            <strong>Signature</strong>
            <strong>Date</strong> (up to three weeks delay from end of first cycle accpetalbe)</p>
                
            <br>
            <table width="200">
                <caption>Communication Log:</caption>

                <tbody>
                    <tr>
                        <th>Objectives</th>

                        <th>Start Date committed to:</th>

                        <th>Achievement evaluation
                            to-date</th>

                        <th>Comments/
                            Next steps recommended</th>
                    </tr>

                    <tr>
                        <td>Turn off lights nightly (at the end of the workday)</td>
                        <td>October 30 2022</td>
                        <td>Completed successfully</td>
                        <td>Ensure continued implementation</td>
                    </tr>

                    <tr>
                        <td>{% render_field formA.objective_1 class="table-input" %} </td>
                        <td>{% render_field formA.start_date_1 type="Date" class="table-input" %} </td>
                        <td>{% render_field formA.achievement_1 class="table-input" %} </td>
                        <td>{% render_field formA.comment_1 class="table-input" %} </td>
                    </tr>

                    <tr>
                        <td>{% render_field formA.objective_2 class="table-input" %} </td>
                        <td>{% render_field formA.start_date_2 type="Date" class="table-input" %} </td>
                        <td>{% render_field formA.achievement_2 class="table-input" %} </td>
                        <td>{% render_field formA.comment_2 class="table-input" %} </td>
                    </tr>

                    <tr>
                        <td>{% render_field formA.objective_3 class="table-input" %} </td>
                        <td>{% render_field formA.start_date_3 type="Date" class="table-input" %} </td>
                        <td>{% render_field formA.achievement_3 class="table-input" %} </td>
                        <td>{% render_field formA.comment_3 class="table-input" %} </td>
                    </tr>

                    <tr>
                        <td>{% render_field formA.objective_4 class="table-input" %} </td>
                        <td>{% render_field formA.start_date_4 type="Date" class="table-input" %} </td>
                        <td>{% render_field formA.achievement_4 class="table-input" %} </td>
                        <td>{% render_field formA.comment_4 class="table-input" %} </td>
                    </tr>
                    
                    <tr>
                        <td>{% render_field formA.objective_5 class="table-input" %} </td>
                        <td>{% render_field formA.start_date_5 type="Date" class="table-input" %} </td>
                        <td>{% render_field formA.achievement_5 class="table-input" %} </td>
                        <td>{% render_field formA.comment_5 class="table-input" %} </td>
                    </tr>

                    <tr>
                        <td>{% render_field formA.objective_6 class="table-input" %} </td>
                        <td>{% render_field formA.start_date_6 type="Date" class="table-input" %} </td>
                        <td>{% render_field formA.achievement_6 class="table-input" %} </td>
                        <td>{% render_field formA.comment_6 class="table-input" %} </td>
                    </tr>

                    <tr>
                        <td>{% render_field formA.objective_7 class="table-input" %} </td>
                        <td>{% render_field formA.start_date_7 type="Date" class="table-input" %} </td>
                        <td>{% render_field formA.achievement_7 class="table-input" %} </td>
                        <td>{% render_field formA.comment_7 class="table-input" %} </td>
                    </tr>

                    <tr>
                        <td>{% render_field formA.objective_8 class="table-input" %} </td>
                        <td>{% render_field formA.start_date_8 type="Date" class="table-input" %} </td>
                        <td>{% render_field formA.achievement_8 class="table-input" %} </td>
                        <td>{% render_field formA.comment_8 class="table-input" %} </td>
                    </tr>

                    <tr>
                        <td>{% render_field formA.objective_9 class="table-input" %} </td>
                        <td>{% render_field formA.start_date_9 type="Date" class="table-input" %} </td>
                        <td>{% render_field formA.achievement_9 class="table-input" %} </td>
                        <td>{% render_field formA.comment_9 class="table-input" %} </td>
                    </tr>

                    <tr>
                        <td>{% render_field formA.objective_10 class="table-input" %} </td>
                        <td>{% render_field formA.start_date_10 type="Date" class="table-input" %} </td>
                        <td>{% render_field formA.achievement_10 class="table-input" %} </td>
                        <td>{% render_field formA.comment_10 class="table-input" %} </td>
                    </tr>
                </tbody>
            </table>

            <br>


        <br><br>
        <div class="btns-group">
            <button type="submit" class="btn">Submit & Contiue</button>
        </div>
    </div>


</form>

{% endblock content %}

main/templates/main/iso_plan.html
{% extends 'main/iso_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Start Here{% endblock title %}

{% block content %}

<div class="container">
    <h3><a href="{% url 'accounts:dashboard' %}">Back to dashboard</a></h3>
</div>

<form class="form">

<h1 class="text-center">Registration form</h1>


        <div class="form-step form-step-active">
            <h2>Getting Started</h2>
            <p><strong><em>Plan Do Check Act</em></strong></p>
            <p><strong> Plan</strong></p>

            <p>Business Information, Scope and Commitment</p>
            <p>Compliance Obligations, Activities, Aspects and Impacts</p>

            <p><strong>Do</strong></p>
            <p>Risk Assessment, Objective and Policy,</p>
            <p>Emergency Response, Nonconformities,</p>
            <p>Communication, Documnentation</p>

            <p><strong>Check</strong></p>
            <p>Audits and Annual Review</p>
            <p>greenmark registry commitment</p>

            <p><strong>ACT</strong></p>
            <p>Continual improvement</p>


            <br><br>
            <div class="btns-group">
                <a href="{% url 'main:iso_buss_info' %}" class="btn btn-next">Next</a>
            </div>
        </div>

</form>

{% endblock content %}

main/templates/main/view_act.html
{% extends 'accounts/base.html' %}

{% block css %}

{% endblock css %}
{% block title %} View Act {% endblock title %}

{% block content %}

<div class="nav-area">
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Greenmark Online</a>
      <span class="right-float"><a href="{% url 'accounts:dashboard' %}">Bach to Dashboard</a></span>
    </nav>
</div>

<br>

<div class="container">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">ACT</h4>
        <hr>
        <p class="mb-0">Continual improvement</p>
    </div>
</div>


{% for act in modelA %}
<div class="container">
    <div class="card border-success">
        <h5 class="card-header">ANNUAL MANAGEMENT REVIEW</h5>
        <div class="card-body">
            <p><strong>This review should be completed at the end of the year:</strong> it can be done during or right after the fourth Quarter Audit or soon after. The Key Decision Maker/s and the Environment Manager do the following:
                <ol>
                    <li>Evaluate the overall environmental performance in light of the policy and commitment to objectives</li>
        
                    <li>Identify and commit to new objectives taking into account changes in the business during the last year</li>
        
                    <li>Sign off on starting a new ISO 14001:2015 cycle and celebrate success</li>
                </ol>
                </p>
        
                <h3>CONTINUAL IMPROVEMENT</h3>
                <p> <strong> {{ act.buss_name }} </strong> commits to having quarterly and annual reviews, audited by greenmark. </p>
        
                <p> <strong> {{ act.buss_name }} </strong>   commits to continually improve its environmental management system, evidenced by the greenmark online registry.</p>
          
        </div>
    </div>
</div>

{% endfor %}
<br>

<div class="container">
    <a href="{% url 'main:print_doc' %}" class="btn btn-success">Download the ISO 14001:2015 Document</a>
</div>

{% endblock content %}

main/templates/main/view_check.html
{% extends 'accounts/base.html' %}

{% block css %}

{% endblock css %}
{% block title %} View Check {% endblock title %}

{% block content %}

<div class="nav-area">
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Greenmark Online</a>
      <span class="right-float"><a href="{% url 'accounts:dashboard' %}">Bach to Dashboard</a></span>
    </nav>
</div>

<br>

<div class="container">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">CHECK</h4>
        <hr>
        <p class="mb-0">Audits and Annual Review, greenmark registry commitment</p>
    </div>
</div>


{% for check in modelA %}
<div class="container">
    <div class="card border-success">
        <h5 class="card-header">AUDITS AND ANNUAL MANAGEMENT REVIEW</h5>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Objectives</th>
                    <th scope="col">Start Date committed to: </th>
                    <th scope="col">Achievement evaluation to-date</th>
                    <th scope="col">Comments/Next steps recommended</th>
                  </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">#Exmp</th>
                        <td>Turn off lights nightly (at the end of the workday)</td>
                        <td>October 30 2022</td>
                        <td>Completed successfully</td>
                        <td>Ensure continued implementation</td>
                    </tr>
                  <tr>
                    <th scope="row">1</th>
                    <td>{{ check.objective_1 }}</td>
                    <td>{{ check.start_date_1 }}</td>
                    <td>{{ check.achievement_1 }}</td>
                    <td>{{ check.comment_1 }}</td>
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>{{ check.objective_2 }}</td>
                    <td>{{ check.start_date_2 }}</td>
                    <td>{{ check.achievement_2 }}</td>
                    <td>{{ check.comment_2 }}</td>
                  </tr>
                  <tr>
                    <th scope="row">3</th>
                    <td>{{ check.objective_3 }}</td>
                    <td>{{ check.start_date_3 }}</td>
                    <td>{{ check.achievement_3 }}</td>
                    <td>{{ check.comment_3 }}</td>
                  </tr>
                  <tr>
                    <th scope="row">4</th>
                    <td>{{ check.objective_4 }}</td>
                    <td>{{ check.start_date_4 }}</td>
                    <td>{{ check.achievement_4 }}</td>
                    <td>{{ check.comment_4 }}</td>
                  </tr>
                  <tr>
                    <th scope="row">5</th>
                    <td>{{ check.objective_5 }}</td>
                    <td>{{ check.start_date_5 }}</td>
                    <td>{{ check.achievement_5 }}</td>
                    <td>{{ check.comment_5 }}</td>
                  </tr>
                  <tr>
                    <th scope="row">6</th>
                    <td>{{ check.objective_6 }}</td>
                    <td>{{ check.start_date_6 }}</td>
                    <td>{{ check.achievement_6 }}</td>
                    <td>{{ check.comment_6 }}</td>
                  </tr>
                  <tr>
                    <th scope="row">7</th>
                    <td>{{ check.objective_7 }}</td>
                    <td>{{ check.start_date_7 }}</td>
                    <td>{{ check.achievement_7 }}</td>
                    <td>{{ check.comment_7 }}</td>
                  </tr>
                  <tr>
                    <th scope="row">8</th>
                    <td>{{ check.objective_8 }}</td>
                    <td>{{ check.start_date_8 }}</td>
                    <td>{{ check.achievement_8 }}</td>
                    <td>{{ check.comment_8 }}</td>
                  </tr>
                  <tr>
                    <th scope="row">9</th>
                    <td>{{ check.objective_9 }}</td>
                    <td>{{ check.start_date_9 }}</td>
                    <td>{{ check.achievement_9 }}</td>
                    <td>{{ check.comment_9 }}</td>
                  </tr>
                  <tr>
                    <th scope="row">10</th>
                    <td>{{ check.objective_10 }}</td>
                    <td>{{ check.start_date_10 }}</td>
                    <td>{{ check.achievement_10 }}</td>
                    <td>{{ check.comment_10 }}</td>
                  </tr>
                  
                </tbody>
              </table>
        </div>
    </div>
</div>
<br>
{% endfor %}
<br>

{% endblock content %}